<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Проекты интернет-магазина стоматологического оборудования и материалов Медкомпания.рф");
$APPLICATION->SetPageProperty("title", "Раздел Проекты");

$APPLICATION->SetTitle("Проекты");

?><div class="container">
	 <?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"proj",
	Array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALLOW_LINK_REVIEWS" => "N",
		"ALLOW_LINK_SERVICES" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"CONSENT_URL" => "/company/consent/",
		"DESCRIPTION_DETAIL_PROPERTIES" => array(0=>"PROPERTY_SCOPE",1=>"PROPERTY_DATE",2=>"PROPERTY_AUTHOR",3=>"PROPERTY_SITE",),
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(0=>"",1=>"",),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(0=>"",1=>"OBJECTIVE",2=>"SOLUTION_END",3=>"SOLUTION_BEGIN",4=>"SERVICES",5=>"",),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_URL_REVIEWS" => "",
		"DETAIL_URL_SERVICES" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_FORM_ASK" => "Y",
		"DISPLAY_FORM_ORDER" => "Y",
		"DISPLAY_LIST_TAB_ALL" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "/404.php",
		"FORM_ASK" => "5",
		"FORM_ORDER" => "4",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "18",
		"IBLOCK_ID_REVIEWS" => "",
		"IBLOCK_ID_SERVICES" => "#CATALOGS_SERVICES_IBLOCK_ID#",
		"IBLOCK_TYPE" => "content",
		"IBLOCK_TYPE_REVIEWS" => "",
		"IBLOCK_TYPE_SERVICES" => "#CATALOGS_SERVICES_IBLOCK_TYPE#",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(0=>"",1=>"",),
		"LIST_PROPERTY_CODE" => array(0=>"",1=>"OBJECTIVE",2=>"SOLUTION_END",3=>"SOLUTION_BEGIN",4=>"SERVICES",5=>"",),
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "50",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PAGE_URL_REVIEWS" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_FORM_ORDER_PROJECT" => "form_text_11",
		"PROPERTY_GALLERY" => "GALLERY",
		"PROPERTY_IMAGES" => "PICTURES",
		"PROPERTY_OBJECTIVE" => "OBJECTIVE",
		"PROPERTY_SERVICES" => "SERVICES",
		"PROPERTY_SOLUTION_BEGIN" => "SOLUTION_BEGIN",
		"PROPERTY_SOLUTION_END" => "SOLUTION_END",
		"PROPERTY_SOLUTION_IMAGE" => "SOLUTION_PICTURE",
		"SEF_FOLDER" => "/projects/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => array("news"=>"","section"=>"","detail"=>"#ELEMENT_ID#/",),
		"SETTINGS_USE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N"
	)
);?>
</div><?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>