<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Сотрудники интернет-магазина стоматологического оборудования и материалов Медкомпания.рф");
$APPLICATION->SetPageProperty("title", "Раздел Сотрудники");

$APPLICATION->SetTitle("Сотрудники");

?>
<div class="container">
<?php $APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"flat", 
	array(
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "27",
		"SETTINGS_USE" => "Y",
		"LAZYLOAD_USE" => "N",
		"NEWS_COUNT" => "100",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "SYSTEM_SKYPE",
			1 => "SYSTEM_POSITION",
			2 => "SYSTEM_PHONE",
			3 => "SYSTEM_EMAIL",
			4 => "SKYPE",
			5 => "POSITION",
			6 => "PHONE",
			7 => "EMAIL",
			8 => "",
		),
		"CHECK_DATES" => "Y",
		"PROPERTY_POSITION" => "POSITION",
		"PROPERTY_PHONE" => "PHONE",
		"PROPERTY_SKYPE" => "SKYPE",
		"PROPERTY_EMAIL" => "EMAIL",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SHOW_ALL_STUFFS" => "Y",
		"COMPONENT_TEMPLATE" => "flat",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"TEMPLATE_THEME" => "site",
		"MEDIA_PROPERTY" => "",
		"SLIDER_PROPERTY" => "",
		"SEARCH_PAGE" => "/search/",
		"USE_RATING" => "N",
		"USE_SHARE" => "N"
	),
	false
); ?>
</div>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>
