<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Расписание");
?>   
<?$APPLICATION->IncludeComponent(
	"mibok:rasp.timetable", 
	"bootstrap4", 
	array(
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "bootstrap4",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_ALL_VALUE" => array(
			0 => "NAME",
			1 => "PROPERTY_AGE",
			2 => "PROPERTY_TYPE_DIRECTION",
			3 => "PROPERTY_HALL",
			4 => "PROPERTY_TEACHER",
			5 => "PROPERTY_LEVEL",
		),
		"FILTER_MAIN_HEADER" => "PROPERTY_FILIAL",
		"EVENT_MESSAGE_ID" => "51",
		"FILTER_NAME" => "arrMibokTt",
		"IBLOCK_ID" => "44",
		"IBLOCK_TYPE" => "s1_rasp",
		"IBLOCK_ID_RECORD" => "43",
		"IBLOCK_TYPE_RECORD" => "s1_rasp",
		"IS_BOOTSTRAP_CSS" => "Y",
		"IS_BOOTSTRAP_JS" => "Y",
		"IS_OWL_CSS" => "Y",
		"IS_OWL_JS" => "Y",
		"IS_PS_CSS" => "Y",
		"IS_PS_JS" => "Y",
		"LIST_SETTINGS_MODAL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_SETTINGS_MODAL_NAME" => "NAME",
		"LIST_SETTINGS_MODAL_PROPERTY_CODE" => array(
			0 => "PROPERTY_AGE",
			1 => "PROPERTY_TYPE_DIRECTION",
			2 => "PROPERTY_HALL",
			3 => "PROPERTY_TEACHER",
			4 => "PROPERTY_LEVEL",
			5 => "PROPERTY_FILIAL",
			6 => "",
		),
		"LIST_SETTINGS_NAME" => "NAME",
		"LIST_SETTINGS_PROP1" => "PROPERTY_HALL",
		"LIST_SETTINGS_PROP2" => "PROPERTY_TEACHER",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "",
		"SET_TITLE" => "Y",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"PROPERTY_CODES_RECORD" => array(
			0 => "193",
			1 => "194",
			2 => "NAME",
		),
		"PROPERTY_CODES_RECORD_REQUIRED" => array(
			0 => "193",
			1 => "194",
		),
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/rasp/",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"CHANGE_BOOTSTRAP" => "N",
		"IS_BOOTSTRAP_DP_JS" => "Y",
		"IS_BOOTSTRAP_DP_CSS" => "Y",
		"FILTER_DATE_RANGE" => "Y",
		"SIGN_HEAD" => "Расписание",
		"SIGN_RECORD" => "Записаться",
		"SIGN_FILTER" => "К сожалению, в расписании пока ничего нет по данным параметрам фильтра",
		"SIGN_NO_DAY" => "Нет данных"
	),
	false
);?>
    
    <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>