<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Контакты, Медкомпания.рф, магазин стом товаров, стоматологические товары, адрес, доставка, Центральный федеральный округ, Москва, Московская область, Тверь, Тверская область, Калуга, Калужская область, Кострома, Костромская область, Владимир, Владимирская область, Ярославль, Ярославская область, Иваново, Ивановская область, Нижний новгород, Нижненовгородская область");
$APPLICATION->SetPageProperty("title", "Контакты");
$APPLICATION->SetTitle("Контактная информация и адреса Медкомпании.рф");
$APPLICATION->SetPageProperty("description", "Контактная информация о адресах точек продаж магазина Медкомпания.рф");
$APPLICATION->SetPageProperty("title", "Раздел Контакты") ?><?php

$APPLICATION->SetTitle("Контакты");

?><?$APPLICATION->IncludeComponent(
	"bitrix:map.yandex.view", 
	"map", 
	array(
		"API_KEY" => "",
		"CONTROLS" => array(
			0 => "ZOOM",
			1 => "MINIMAP",
			2 => "TYPECONTROL",
			3 => "SCALELINE",
			4 => "SEARCH",
		),
		"INIT_MAP_TYPE" => "MAP",
		"MAP_DATA" => "a:4:{s:10:\"yandex_lat\";d:57.60630580633294;s:10:\"yandex_lon\";d:39.87282762770897;s:12:\"yandex_scale\";i:15;s:10:\"PLACEMARKS\";a:3:{i:0;a:3:{s:3:\"LON\";d:39.872291969948;s:3:\"LAT\";d:57.605779992529;s:4:\"TEXT\";s:42:\"Главный офис Ярославля\";}i:1;a:3:{s:3:\"LON\";d:41.000001849834;s:3:\"LAT\";d:56.998496308594;s:4:\"TEXT\";s:38:\"Главный офис Иваново\";}i:2;a:3:{s:3:\"LON\";d:40.369577653709214;s:3:\"LAT\";d:56.12070108251329;s:4:\"TEXT\";s:42:\"Главный офис Владимира\";}}}",
		"MAP_HEIGHT" => "500",
		"MAP_ID" => "",
		"MAP_WIDTH" => "100%",
		"OPTIONS" => array(
			0 => "ENABLE_SCROLL_ZOOM",
			1 => "ENABLE_DBLCLICK_ZOOM",
			2 => "ENABLE_DRAGGING",
		),
		"COMPONENT_TEMPLATE" => "map",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);?>
<div class="container">
	 <?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"maps", 
	array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"API_KEY_MAP" => "",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "N",
		"COMPONENT_TEMPLATE" => "maps",
		"CONTACT_ID" => "",
		"DESCRIPTION_SHOW" => "Y",
		"DESCRIPTION_TEXT" => "",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILE_404" => "/404.php",
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "10",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"MAP_VENDOR" => "google",
		"MEDIA_PROPERTY" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Контакты",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_ADDRESS" => "ADDRESS",
		"PROPERTY_CITY" => "CITY",
		"PROPERTY_CODE" => array(
			0 => "ADDRESS",
			1 => "WORK_TIME",
			2 => "PHONE",
			3 => "EMAIL",
			4 => "CITY",
			5 => "",
		),
		"PROPERTY_EMAIL" => "EMAIL",
		"PROPERTY_MAP" => "MAP",
		"PROPERTY_OPENING_HOURS" => "OPENING_HOURS",
		"PROPERTY_PHONE" => "PHONE",
		"PROPERTY_STORE_ID" => "STORE_ID",
		"PROPERTY_WORK_TIME" => "WORK_TIME",
		"REGIONALITY_PROPERTY" => "REGIONS",
		"REGIONALITY_USE" => "N",
		"SEARCH_PAGE" => "/search/",
		"SETTINGS_USE" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_FORM" => "Y",
		"SHOW_LIST" => "NONE",
		"SHOW_MAP" => "Y",
		"SLIDER_PROPERTY" => "",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"TEMPLATE_THEME" => "blue",
		"TITLE_SHOW" => "Y",
		"TITLE_TEXT" => "",
		"USE_RATING" => "N",
		"USE_SHARE" => "N",
		"WEB_FORM_CONSENT_URL" => "/company/consent/",
		"WEB_FORM_ID" => "2",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);?>
</div>
 <br><?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>